version: '3.7'
services:
  node-app:
    build: 
      context: .
      target: development
      # args:
      #   - NODE_ENV=DEV
    volumes:
      - ./src:/app/src:ro
      - ./tests:/app/tests
    environment:
      - NODE_ENV=DEV
    command: npm run docker-dev
    